server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  application:
    name: Item-Management

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


  sql:
    init:
      mode: always

  main:
    banner-mode: off

  output:
    ansi:
      enabled: ALWAYS

#logging:
#  level:
#    root: warn