server:
  port: ${SERVER_PORT}

spring:
  application:
    name: Item-Management

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${SCHEMA}
#    show-sql: true

  sql:
    init:
      mode: always

  main:
    banner-mode: off

  output:
    ansi:
      enabled: ALWAYS

#logging:
#  level:
#    root: warn